# Generated by Django 4.2.13 on 2024-06-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_comment_options_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
