# Generated by Django 4.2.13 on 2024-06-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
