# Generated by Django 4.2.13 on 2024-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_post',
            name='summary',
            field=models.TextField(),
        ),
    ]
