# Generated by Django 4.2.13 on 2024-06-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_post_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'ordering': ['created_on']},
        ),
    ]
