# Generated by Django 4.2.13 on 2024-06-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_news_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'ordering': ['-created_on']},
        ),
    ]
